# Generated by Django 5.1.15 on 2026-01-07 09:17

import ckeditor.fields
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=120)),
                ('issued_at', models.DateField()),
                ('credential_url', models.URLField(blank=True)),
                ('credly_share_badge_id', models.CharField(blank=True, max_length=64)),
                ('credly_host', models.URLField(blank=True, default='https://www.credly.com')),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(max_length=280)),
                ('role_type', models.CharField(choices=[('SOC', 'SOC'), ('DFIR', 'DFIR'), ('SIEM', 'SIEM'), ('Cloud', 'Cloud Security'), ('AppSec', 'Application Security'), ('GRC', 'GRC')], default='SOC', max_length=16)),
                ('problem_statement', ckeditor.fields.RichTextField(blank=True)),
                ('approach', ckeditor.fields.RichTextField(blank=True)),
                ('outcomes', ckeditor.fields.RichTextField(blank=True)),
                ('tools', models.CharField(blank=True, help_text='Comma-separated tools', max_length=300)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('doc_type', models.CharField(choices=[('IR', 'Incident Report'), ('HUNT', 'Threat Hunt'), ('DETECTION', 'Detection Rule'), ('PCAP', 'PCAP Analysis'), ('AUDIT', 'Audit Checklist'), ('NOTES', 'Lab Notes')], max_length=16)),
                ('summary', models.CharField(blank=True, max_length=280)),
                ('file', models.FileField(upload_to='documents/')),
                ('is_redacted_public', models.BooleanField(default=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
